<div class="post content">
	<a href="<?php echo _url('index', 'index'); ?>"><?php echo _t('gen.action.back_to_rss_feeds'); ?></a>

	<h1><?php echo _t('index.about'); ?></h1>

	<dl class="infos">
		<dt><?php echo _t('index.about.project_website'); ?></dt>
		<dd><a href="<?php echo FRESHRSS_WEBSITE; ?>"><?php echo FRESHRSS_WEBSITE; ?></a></dd>

		<dt><?php echo _t('index.about.bugs_reports'); ?></dt>
		<dd><?php echo _t('index.about.github'); ?></dd>

		<dt><?php echo _t('index.about.license'); ?></dt>
		<dd><?php echo _t('index.about.agpl3'); ?></dd>

		<?php if (FreshRSS_Auth::hasAccess()): ?>
		<dt><?php echo _t('index.about.version'); ?></dt>
		<dd><?php echo FRESHRSS_VERSION; ?></dd>
		<?php endif; ?>
	</dl>

	<p><?php echo _t('index.about.freshrss_description'); ?></p>

	<h1><?php echo _t('index.about.credits'); ?></h1>
	<p><?php echo _t('index.about.credits_content'); ?></p>

   <h1>About Ada Planet</h1>
   <p>If you have any questions, suggestions about links to add to the Planet or problems with the page, please use one of the options on the <a href="https://www.laeran.pl/contact.html">contact page</a></p>
   <p>All changed files and list of feeds used by Ada Planet can be found on <a href="https://github.com/thindil/adaplanet">Github</a> under this same licenses as FreshRSS and RSSBridge.</p>
</div>
